### ISSUE TITLE
Create a Package with the functionalities

### ISSUE THREAD

**Issue by DEKHTIARJonathan** [pirate/pocket-archive-stream#3]
Hello dear friend,

I would be extremely interested to add the features you developed to a personal project.
Do you plan on releasing a package on PyPI ?

The following could be awesome:

```
from archive_stream import Archiver

saver = Archiver("http://www.mygreaturl.com/article/")
saver.export_screenshot("/path/to/screenshot/filename.png")
saver.export_pdf("/path/to/pdf/filename.pdf")
```

That would be absolutely awesome if you could release it, and I might help you if you need anything.

For the record, I would like to integrate your solution to this platform : https://www.feedcrunch.io/@dataradar

**Comment by pirate** [comment]
I think your needs would be better served writing a simple archiver yourself, the archiving functionality is only three commands:

- `wget --no-clobber --page-requisites --adjust-extension --convert-links --no-parent https://example.com/url`
- `google-chrome --headless --disable-gpu --print-to-pdf https://example.com/url`
- `google-chrome --headless --disable-gpu --screenshot 1440,900 https://example.com/url`
- `curl https://www.google.com/s2/favicons?domain=example.com > favicon.ico` (optional)

It's hard to justify making it a package because it depends on Google Chrome, doesn't have many configurable options, and produces a fairly rigid output structure.
